package vista;

import javax.swing.table.DefaultTableModel;

public class FrmEliminarLibro extends javax.swing.JFrame {

    /**
     * Creates new form FrmEliminarLibro
     */
    public FrmEliminarLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEliminarL = new javax.swing.JLabel();
        btnEliminarL = new javax.swing.JButton();
        btnCancelarEL = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel dtmL = new DefaultTableModel();
        tblEliminarL = new javax.swing.JTable();
        lblDescripcionEL = new javax.swing.JLabel();
        lblTituloEL = new javax.swing.JLabel();
        lblAutorEL = new javax.swing.JLabel();
        lblCategoriaEL = new javax.swing.JLabel();
        txtTituloEL = new javax.swing.JTextField();
        txtAutorEL = new javax.swing.JTextField();
        txtCategoriaEL = new javax.swing.JTextField();
        lblCodigoEL = new javax.swing.JLabel();
        txtCodigoEL = new javax.swing.JTextField();
        lblPaginasEL = new javax.swing.JLabel();
        txtPaginasEL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar libros");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEliminarL.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        lblEliminarL.setText("ELIMINAR LIBROS");
        getContentPane().add(lblEliminarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnEliminarL.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnEliminarL.setText("ELIMINAR");
        getContentPane().add(btnEliminarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 130, 60));

        btnCancelarEL.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnCancelarEL.setText("CANCELAR");
        getContentPane().add(btnCancelarEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, 130, 60));

        tblEliminarL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblEliminarL);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 690, 290));

        lblDescripcionEL.setText("Dar doble clic en el registro para seleccionarlo");
        getContentPane().add(lblDescripcionEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        lblTituloEL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloEL.setText("Título del libro");
        getContentPane().add(lblTituloEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        lblAutorEL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblAutorEL.setText("Autor del libro");
        getContentPane().add(lblAutorEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        lblCategoriaEL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCategoriaEL.setText("Categoría del libro");
        getContentPane().add(lblCategoriaEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        txtTituloEL.setEditable(false);
        getContentPane().add(txtTituloEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 340, -1));

        txtAutorEL.setEditable(false);
        getContentPane().add(txtAutorEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 330, -1));

        txtCategoriaEL.setEditable(false);
        txtCategoriaEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaELActionPerformed(evt);
            }
        });
        getContentPane().add(txtCategoriaEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 340, -1));

        lblCodigoEL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCodigoEL.setText("Código del libro");
        getContentPane().add(lblCodigoEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));
        getContentPane().add(txtCodigoEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 170, -1));

        lblPaginasEL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPaginasEL.setText("Número de páginas del libro");
        getContentPane().add(lblPaginasEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        txtPaginasEL.setEditable(false);
        txtPaginasEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaginasELActionPerformed(evt);
            }
        });
        getContentPane().add(txtPaginasEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCategoriaELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaELActionPerformed

    private void txtPaginasELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaginasELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaginasELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEliminarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEliminarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEliminarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEliminarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEliminarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarEL;
    public javax.swing.JButton btnEliminarL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutorEL;
    private javax.swing.JLabel lblCategoriaEL;
    private javax.swing.JLabel lblCodigoEL;
    private javax.swing.JLabel lblDescripcionEL;
    private javax.swing.JLabel lblEliminarL;
    private javax.swing.JLabel lblPaginasEL;
    private javax.swing.JLabel lblTituloEL;
    public javax.swing.JTable tblEliminarL;
    public javax.swing.JTextField txtAutorEL;
    public javax.swing.JTextField txtCategoriaEL;
    public javax.swing.JTextField txtCodigoEL;
    public javax.swing.JTextField txtPaginasEL;
    public javax.swing.JTextField txtTituloEL;
    // End of variables declaration//GEN-END:variables
}
