package vista;

import javax.swing.table.DefaultTableModel;

public class FrmEliminarAutor extends javax.swing.JFrame {

    /**
     * Creates new form FrmEliminarAutor
     */
    public FrmEliminarAutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEliminarA = new javax.swing.JLabel();
        btnEliminarA = new javax.swing.JButton();
        btnCancelarEA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel dtmA = new DefaultTableModel();
        tblEliminarA = new javax.swing.JTable();
        lblDescripcionEA = new javax.swing.JLabel();
        lblNombreEA = new javax.swing.JLabel();
        lblPaisEA = new javax.swing.JLabel();
        lblEdadEA = new javax.swing.JLabel();
        txtNombreEA = new javax.swing.JTextField();
        txtPaisEA = new javax.swing.JTextField();
        txtEdadEA = new javax.swing.JTextField();
        lblCodigoEA = new javax.swing.JLabel();
        txtCodigoEA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar autores");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEliminarA.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        lblEliminarA.setText("ELIMINAR AUTORES");
        getContentPane().add(lblEliminarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnEliminarA.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnEliminarA.setText("ELIMINAR");
        getContentPane().add(btnEliminarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 130, 60));

        btnCancelarEA.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnCancelarEA.setText("CANCELAR");
        getContentPane().add(btnCancelarEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, 130, 60));

        tblEliminarA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblEliminarA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 690, 340));

        lblDescripcionEA.setText("Dar doble clic en el registro para seleccionarlo");
        getContentPane().add(lblDescripcionEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        lblNombreEA.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombreEA.setText("Nombre del autor");
        getContentPane().add(lblNombreEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        lblPaisEA.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPaisEA.setText("País de origen del autor");
        getContentPane().add(lblPaisEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        lblEdadEA.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblEdadEA.setText("Edad del autor");
        getContentPane().add(lblEdadEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        txtNombreEA.setEditable(false);
        getContentPane().add(txtNombreEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 220, -1));

        txtPaisEA.setEditable(false);
        getContentPane().add(txtPaisEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 220, -1));

        txtEdadEA.setEditable(false);
        txtEdadEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadEAActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdadEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 220, -1));

        lblCodigoEA.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCodigoEA.setText("Código del autor");
        getContentPane().add(lblCodigoEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));
        getContentPane().add(txtCodigoEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadEAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadEAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEliminarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEliminarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEliminarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEliminarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEliminarAutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarEA;
    public javax.swing.JButton btnEliminarA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoEA;
    private javax.swing.JLabel lblDescripcionEA;
    private javax.swing.JLabel lblEdadEA;
    private javax.swing.JLabel lblEliminarA;
    private javax.swing.JLabel lblNombreEA;
    private javax.swing.JLabel lblPaisEA;
    public javax.swing.JTable tblEliminarA;
    public javax.swing.JTextField txtCodigoEA;
    public javax.swing.JTextField txtEdadEA;
    public javax.swing.JTextField txtNombreEA;
    public javax.swing.JTextField txtPaisEA;
    // End of variables declaration//GEN-END:variables
}
