package vista;

public class FrmInsertarLibro extends javax.swing.JFrame {

    /**
     * Creates new form FrmInsertarLibrp
     */
    public FrmInsertarLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopInsertarLibro = new javax.swing.JOptionPane();
        lblTituloInsertarL = new javax.swing.JLabel();
        lblTituloL = new javax.swing.JLabel();
        lblAutorL = new javax.swing.JLabel();
        lblCategoriaL = new javax.swing.JLabel();
        txtTituloIL = new javax.swing.JTextField();
        txtPaginasIL = new javax.swing.JTextField();
        btnRegistrarL = new javax.swing.JButton();
        btnCancelarIL = new javax.swing.JButton();
        lblTextoIns = new javax.swing.JLabel();
        lblFechaInsL = new javax.swing.JLabel();
        cmbAutorIL = new javax.swing.JComboBox<>();
        cmbCategoriaIL = new javax.swing.JComboBox<>();
        lblPaginasL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insertar libros");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloInsertarL.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        lblTituloInsertarL.setText("REGISTRO DE LIBROS");
        getContentPane().add(lblTituloInsertarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblTituloL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloL.setText("Título del libro:");
        getContentPane().add(lblTituloL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        lblAutorL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblAutorL.setText("Autor del libro:");
        getContentPane().add(lblAutorL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        lblCategoriaL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCategoriaL.setText("Categoría del libro:");
        getContentPane().add(lblCategoriaL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));
        getContentPane().add(txtTituloIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 260, -1));

        txtPaginasIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaginasILActionPerformed(evt);
            }
        });
        getContentPane().add(txtPaginasIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 260, -1));

        btnRegistrarL.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnRegistrarL.setText("REGISTRAR");
        getContentPane().add(btnRegistrarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 130, 60));

        btnCancelarIL.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnCancelarIL.setText("CANCELAR");
        getContentPane().add(btnCancelarIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 130, 60));

        lblTextoIns.setText("* Fecha de Inserción:");
        getContentPane().add(lblTextoIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));
        getContentPane().add(lblFechaInsL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 140, 20));

        getContentPane().add(cmbAutorIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 260, -1));

        cmbCategoriaIL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantil", "Fantasía", "Romance", "Comedia", "Terror", "Misterio", "Acción" }));
        getContentPane().add(cmbCategoriaIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 260, -1));

        lblPaginasL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPaginasL.setText("Número de páginas del libro:");
        getContentPane().add(lblPaginasL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaginasILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaginasILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaginasILActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInsertarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInsertarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInsertarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInsertarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInsertarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarIL;
    public javax.swing.JButton btnRegistrarL;
    public javax.swing.JComboBox<String> cmbAutorIL;
    public javax.swing.JComboBox<String> cmbCategoriaIL;
    public javax.swing.JOptionPane jopInsertarLibro;
    private javax.swing.JLabel lblAutorL;
    private javax.swing.JLabel lblCategoriaL;
    public javax.swing.JLabel lblFechaInsL;
    private javax.swing.JLabel lblPaginasL;
    private javax.swing.JLabel lblTextoIns;
    private javax.swing.JLabel lblTituloInsertarL;
    private javax.swing.JLabel lblTituloL;
    public javax.swing.JTextField txtPaginasIL;
    public javax.swing.JTextField txtTituloIL;
    // End of variables declaration//GEN-END:variables
}
