package vista;

import javax.swing.table.DefaultTableModel;

public class FrmModificarLibro extends javax.swing.JFrame {

    /**
     * Creates new form FrmModificarLibro
     */
    public FrmModificarLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopModificarL = new javax.swing.JOptionPane();
        lblModificarL = new javax.swing.JLabel();
        btnModificarL = new javax.swing.JButton();
        btnCancelarMDL = new javax.swing.JButton();
        lblTextoActMDL = new javax.swing.JLabel();
        lblFechaActL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel dtmL = new DefaultTableModel();
        tblModificarL = new javax.swing.JTable();
        lblNombreMDL = new javax.swing.JLabel();
        txtCodigoMDL = new javax.swing.JTextField();
        lblDescripcionMDL = new javax.swing.JLabel();
        lblAutorMDL = new javax.swing.JLabel();
        lblCategoriaMDL = new javax.swing.JLabel();
        txtPaginasMDL = new javax.swing.JTextField();
        cmbAutorMDL = new javax.swing.JComboBox<>();
        cmbCategoriaMDL = new javax.swing.JComboBox<>();
        lblPaginasMDL = new javax.swing.JLabel();
        lblTituloMDL = new javax.swing.JLabel();
        txtTituloMDL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar libros");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblModificarL.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        lblModificarL.setText("MODIFICAR LIBROS");
        getContentPane().add(lblModificarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnModificarL.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnModificarL.setText("MODIFICAR");
        getContentPane().add(btnModificarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 130, 60));

        btnCancelarMDL.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnCancelarMDL.setText("CANCELAR");
        getContentPane().add(btnCancelarMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, 130, 60));

        lblTextoActMDL.setText("* Fecha de Modificación:");
        getContentPane().add(lblTextoActMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 770, -1, -1));
        getContentPane().add(lblFechaActL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 770, 140, 20));

        tblModificarL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblModificarL);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 690, 290));

        lblNombreMDL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombreMDL.setText("Código del libro:");
        getContentPane().add(lblNombreMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        txtCodigoMDL.setEditable(false);
        getContentPane().add(txtCodigoMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 260, -1));

        lblDescripcionMDL.setText("Dar doble clic en el registro para modificarlo");
        getContentPane().add(lblDescripcionMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        lblAutorMDL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblAutorMDL.setText("Autor del libro:");
        getContentPane().add(lblAutorMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        lblCategoriaMDL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCategoriaMDL.setText("Categoría del libro:");
        getContentPane().add(lblCategoriaMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        txtPaginasMDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaginasMDLActionPerformed(evt);
            }
        });
        getContentPane().add(txtPaginasMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 260, -1));

        getContentPane().add(cmbAutorMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 260, -1));

        cmbCategoriaMDL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantil", "Fantasía", "Romance", "Comedia", "Terror", "Misterio", "Acción" }));
        getContentPane().add(cmbCategoriaMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 260, -1));

        lblPaginasMDL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPaginasMDL.setText("Número de páginas del libro:");
        getContentPane().add(lblPaginasMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        lblTituloMDL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloMDL.setText("Título del libro:");
        getContentPane().add(lblTituloMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));
        getContentPane().add(txtTituloMDL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 260, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaginasMDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaginasMDLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaginasMDLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModificarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarMDL;
    public javax.swing.JButton btnModificarL;
    public javax.swing.JComboBox<String> cmbAutorMDL;
    public javax.swing.JComboBox<String> cmbCategoriaMDL;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JOptionPane jopModificarL;
    private javax.swing.JLabel lblAutorMDL;
    private javax.swing.JLabel lblCategoriaMDL;
    private javax.swing.JLabel lblDescripcionMDL;
    public javax.swing.JLabel lblFechaActL;
    private javax.swing.JLabel lblModificarL;
    private javax.swing.JLabel lblNombreMDL;
    private javax.swing.JLabel lblPaginasMDL;
    private javax.swing.JLabel lblTextoActMDL;
    private javax.swing.JLabel lblTituloMDL;
    public javax.swing.JTable tblModificarL;
    public javax.swing.JTextField txtCodigoMDL;
    public javax.swing.JTextField txtPaginasMDL;
    public javax.swing.JTextField txtTituloMDL;
    // End of variables declaration//GEN-END:variables
}
