package vista;

public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTItuloMenu = new javax.swing.JLabel();
        mbBarraMenu = new javax.swing.JMenuBar();
        jmAutor = new javax.swing.JMenu();
        jmiInsertarA = new javax.swing.JMenuItem();
        jmiMostrarA = new javax.swing.JMenuItem();
        jmiModificarA = new javax.swing.JMenuItem();
        jmiEliminarA = new javax.swing.JMenuItem();
        jmLibro = new javax.swing.JMenu();
        jmiInsertarL = new javax.swing.JMenuItem();
        jmiMostrarL = new javax.swing.JMenuItem();
        jmiModificarL = new javax.swing.JMenuItem();
        jmiEliminarL = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTItuloMenu.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        lblTItuloMenu.setText("BIBLIOTECA");
        getContentPane().add(lblTItuloMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jmAutor.setText("Autor");

        jmiInsertarA.setText("Insertar autores");
        jmiInsertarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInsertarAActionPerformed(evt);
            }
        });
        jmAutor.add(jmiInsertarA);

        jmiMostrarA.setText("Mostrar autores");
        jmAutor.add(jmiMostrarA);

        jmiModificarA.setText("Modificar autores");
        jmAutor.add(jmiModificarA);

        jmiEliminarA.setText("Eliminar autores");
        jmAutor.add(jmiEliminarA);

        mbBarraMenu.add(jmAutor);

        jmLibro.setText("Libro");

        jmiInsertarL.setText("Insertar libros");
        jmLibro.add(jmiInsertarL);

        jmiMostrarL.setText("Mostrar libros");
        jmLibro.add(jmiMostrarL);

        jmiModificarL.setText("Modificar libros");
        jmLibro.add(jmiModificarL);

        jmiEliminarL.setText("Eliminar libros");
        jmLibro.add(jmiEliminarL);

        mbBarraMenu.add(jmLibro);

        setJMenuBar(mbBarraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiInsertarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInsertarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiInsertarAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmAutor;
    private javax.swing.JMenu jmLibro;
    public javax.swing.JMenuItem jmiEliminarA;
    public javax.swing.JMenuItem jmiEliminarL;
    public javax.swing.JMenuItem jmiInsertarA;
    public javax.swing.JMenuItem jmiInsertarL;
    public javax.swing.JMenuItem jmiModificarA;
    public javax.swing.JMenuItem jmiModificarL;
    public javax.swing.JMenuItem jmiMostrarA;
    public javax.swing.JMenuItem jmiMostrarL;
    private javax.swing.JLabel lblTItuloMenu;
    private javax.swing.JMenuBar mbBarraMenu;
    // End of variables declaration//GEN-END:variables
}
