package vista;

import javax.swing.table.DefaultTableModel;

public class FrmModificarAutor extends javax.swing.JFrame {

    /**
     * Creates new form FrmModificarAutor
     */
    public FrmModificarAutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopModificarA = new javax.swing.JOptionPane();
        lblModificarA = new javax.swing.JLabel();
        lblNombreMDA = new javax.swing.JLabel();
        lblPaisMDA = new javax.swing.JLabel();
        lblEdadMDA = new javax.swing.JLabel();
        txtNombreMDA = new javax.swing.JTextField();
        txtPaisMDA = new javax.swing.JTextField();
        txtEdadMDA = new javax.swing.JTextField();
        btnModificarA = new javax.swing.JButton();
        btnCancelarMDA = new javax.swing.JButton();
        lblTextoActMDA = new javax.swing.JLabel();
        lblFechaActMDA = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel dtmA = new DefaultTableModel();
        tblModificarA = new javax.swing.JTable();
        lblCodigoMDA = new javax.swing.JLabel();
        txtCodigoMDA = new javax.swing.JTextField();
        lblDescripcionMDA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar autores");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblModificarA.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        lblModificarA.setText("MODIFICAR AUTORES");
        getContentPane().add(lblModificarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblNombreMDA.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombreMDA.setText("Nombre del autor:");
        getContentPane().add(lblNombreMDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        lblPaisMDA.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPaisMDA.setText("País de origen del autor:");
        getContentPane().add(lblPaisMDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        lblEdadMDA.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblEdadMDA.setText("Edad del autor:");
        getContentPane().add(lblEdadMDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));
        getContentPane().add(txtNombreMDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 260, -1));
        getContentPane().add(txtPaisMDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 260, -1));

        txtEdadMDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadMDAActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdadMDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 260, -1));

        btnModificarA.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnModificarA.setText("MODIFICAR");
        getContentPane().add(btnModificarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 130, 60));

        btnCancelarMDA.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnCancelarMDA.setText("CANCELAR");
        getContentPane().add(btnCancelarMDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, 130, 60));

        lblTextoActMDA.setText("* Fecha de Modificación:");
        getContentPane().add(lblTextoActMDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 770, -1, -1));
        getContentPane().add(lblFechaActMDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 770, 140, 20));

        tblModificarA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblModificarA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 690, 340));

        lblCodigoMDA.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCodigoMDA.setText("Código del autor:");
        getContentPane().add(lblCodigoMDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        txtCodigoMDA.setEditable(false);
        getContentPane().add(txtCodigoMDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 260, -1));

        lblDescripcionMDA.setText("Dar doble clic en el registro para modificarlo");
        getContentPane().add(lblDescripcionMDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadMDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadMDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadMDAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModificarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModificarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModificarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModificarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModificarAutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarMDA;
    public javax.swing.JButton btnModificarA;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JOptionPane jopModificarA;
    private javax.swing.JLabel lblCodigoMDA;
    private javax.swing.JLabel lblDescripcionMDA;
    private javax.swing.JLabel lblEdadMDA;
    public javax.swing.JLabel lblFechaActMDA;
    private javax.swing.JLabel lblModificarA;
    private javax.swing.JLabel lblNombreMDA;
    private javax.swing.JLabel lblPaisMDA;
    private javax.swing.JLabel lblTextoActMDA;
    public javax.swing.JTable tblModificarA;
    public javax.swing.JTextField txtCodigoMDA;
    public javax.swing.JTextField txtEdadMDA;
    public javax.swing.JTextField txtNombreMDA;
    public javax.swing.JTextField txtPaisMDA;
    // End of variables declaration//GEN-END:variables
}
