/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ana
 */
public class FrmActualizar extends javax.swing.JFrame {

    /**
     * Creates new form FrmActualizar
     */
    public FrmActualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopMensaje = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        lblTituloActualizar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCapital = new javax.swing.JLabel();
        lblPoblacion = new javax.swing.JLabel();
        txtIDA = new javax.swing.JTextField();
        txtNombrePaisA = new javax.swing.JTextField();
        txtCapitalA = new javax.swing.JTextField();
        txtPoblacionA = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel dtm = new DefaultTableModel();
        tblActualizar = new javax.swing.JTable();
        lblExplicacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloActualizar.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblTituloActualizar.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloActualizar.setText("ACTUALIZAR PAÍS");
        jPanel1.add(lblTituloActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 80));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setBackground(new java.awt.Color(0, 204, 204));
        btnActualizar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 102, 102));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 140, 60));

        lblID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(102, 102, 102));
        lblID.setText("ID País:");
        jPanel2.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(102, 102, 102));
        lblNombre.setText("Nombre del País:");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblCapital.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCapital.setForeground(new java.awt.Color(102, 102, 102));
        lblCapital.setText("Capital:");
        jPanel2.add(lblCapital, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        lblPoblacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPoblacion.setForeground(new java.awt.Color(102, 102, 102));
        lblPoblacion.setText("Población:");
        jPanel2.add(lblPoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        txtIDA.setEditable(false);
        txtIDA.setBackground(new java.awt.Color(102, 102, 102));
        txtIDA.setForeground(new java.awt.Color(255, 255, 255));
        txtIDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDAActionPerformed(evt);
            }
        });
        jPanel2.add(txtIDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 250, -1));
        jPanel2.add(txtNombrePaisA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 249, -1));
        jPanel2.add(txtCapitalA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 249, -1));
        jPanel2.add(txtPoblacionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 249, -1));

        btnCancelar.setBackground(new java.awt.Color(0, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 102, 102));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 130, 50));

        tblActualizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblActualizar);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 530, 270));

        lblExplicacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblExplicacion.setForeground(new java.awt.Color(102, 102, 102));
        lblExplicacion.setText("De doble clic en el registro para modificarlo");
        jPanel2.add(lblExplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 590, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JOptionPane jopMensaje;
    private javax.swing.JLabel lblCapital;
    private javax.swing.JLabel lblExplicacion;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPoblacion;
    private javax.swing.JLabel lblTituloActualizar;
    public javax.swing.JTable tblActualizar;
    public javax.swing.JTextField txtCapitalA;
    public javax.swing.JTextField txtIDA;
    public javax.swing.JTextField txtNombrePaisA;
    public javax.swing.JTextField txtPoblacionA;
    // End of variables declaration//GEN-END:variables
}
