package vista;

import javax.swing.table.DefaultTableModel;

public class FrmAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdministrador
     */
    public FrmAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jopAdministrador = new javax.swing.JOptionPane();
        pnlFondo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel dtm = new DefaultTableModel();
        tblUsuarios = new javax.swing.JTable();
        pnlHerramientas = new javax.swing.JPanel();
        lblInsertar = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        lblReporteU = new javax.swing.JLabel();
        pnlDatosU = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblTItulo = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblEdadU = new javax.swing.JLabel();
        lblRangoU = new javax.swing.JLabel();
        lblIDU = new javax.swing.JLabel();
        lblNombreU = new javax.swing.JLabel();
        lblUsuarioU = new javax.swing.JLabel();
        lblContrasenaU = new javax.swing.JLabel();
        lblApellidoU = new javax.swing.JLabel();
        cmbRango = new javax.swing.JComboBox<>();
        psfContrasena = new javax.swing.JPasswordField();
        pnlUsuario = new javax.swing.JPanel();
        lblImagenU = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblIdUser = new javax.swing.JLabel();
        lblTipoUsuario1 = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MENÚ ADMINISTRADOR");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setForeground(new java.awt.Color(255, 255, 255));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUsuarios.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        pnlFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 900, 380));

        pnlHerramientas.setBackground(new java.awt.Color(97, 96, 96));
        pnlHerramientas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/insertar.png"))); // NOI18N
        pnlHerramientas.add(lblInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        pnlHerramientas.add(lblModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        pnlHerramientas.add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        pnlHerramientas.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        lblReporteU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        pnlHerramientas.add(lblReporteU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        pnlFondo.add(pnlHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 70, 450));

        pnlDatosU.setBackground(new java.awt.Color(204, 204, 204));
        pnlDatosU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(204, 204, 255));
        txtID.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtID.setForeground(new java.awt.Color(51, 51, 51));
        pnlDatosU.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 230, 30));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(51, 51, 51));
        pnlDatosU.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 30));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        pnlDatosU.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 220, 30));

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(51, 51, 51));
        pnlDatosU.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 220, 30));

        lblTItulo.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        lblTItulo.setForeground(new java.awt.Color(71, 68, 68));
        lblTItulo.setText("DATOS DEL USUARIO");
        pnlDatosU.add(lblTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 290, -1));

        txtEdad.setBackground(new java.awt.Color(255, 255, 255));
        txtEdad.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(51, 51, 51));
        pnlDatosU.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 230, 30));

        lblEdadU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEdadU.setForeground(new java.awt.Color(92, 92, 92));
        lblEdadU.setText("Edad");
        pnlDatosU.add(lblEdadU, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        lblRangoU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRangoU.setForeground(new java.awt.Color(92, 92, 92));
        lblRangoU.setText("Rango");
        pnlDatosU.add(lblRangoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        lblIDU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIDU.setForeground(new java.awt.Color(92, 92, 92));
        lblIDU.setText("ID");
        pnlDatosU.add(lblIDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        lblNombreU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombreU.setForeground(new java.awt.Color(92, 92, 92));
        lblNombreU.setText("Nombre");
        pnlDatosU.add(lblNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        lblUsuarioU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUsuarioU.setForeground(new java.awt.Color(92, 92, 92));
        lblUsuarioU.setText("Usuario");
        pnlDatosU.add(lblUsuarioU, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        lblContrasenaU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContrasenaU.setForeground(new java.awt.Color(92, 92, 92));
        lblContrasenaU.setText("Contraseña");
        pnlDatosU.add(lblContrasenaU, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        lblApellidoU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblApellidoU.setForeground(new java.awt.Color(92, 92, 92));
        lblApellidoU.setText("Apellido");
        pnlDatosU.add(lblApellidoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        cmbRango.setBackground(new java.awt.Color(255, 255, 255));
        cmbRango.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        cmbRango.setForeground(new java.awt.Color(51, 51, 51));
        pnlDatosU.add(cmbRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 230, -1));

        psfContrasena.setBackground(new java.awt.Color(255, 255, 255));
        psfContrasena.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        psfContrasena.setForeground(new java.awt.Color(51, 51, 51));
        pnlDatosU.add(psfContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 220, 30));

        pnlFondo.add(pnlDatosU, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 790, 250));

        pnlUsuario.setBackground(new java.awt.Color(47, 8, 92));
        pnlUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuarioA.png"))); // NOI18N
        pnlUsuario.add(lblImagenU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        lblNombreUsuario.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlUsuario.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 180, 30));

        lblIdUser.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblIdUser.setForeground(new java.awt.Color(217, 199, 231));
        pnlUsuario.add(lblIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 50, 20));

        lblTipoUsuario1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTipoUsuario1.setForeground(new java.awt.Color(217, 199, 231));
        lblTipoUsuario1.setText("Administrador");
        pnlUsuario.add(lblTipoUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 100, 20));

        pnlFondo.add(pnlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 250));

        lblDescripcion.setForeground(new java.awt.Color(51, 51, 51));
        lblDescripcion.setText("Dé doble clic sobre el usuario para seleccionarlo");
        pnlFondo.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cmbRango;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JOptionPane jopAdministrador;
    private javax.swing.JLabel lblApellidoU;
    private javax.swing.JLabel lblContrasenaU;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEdadU;
    public javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblIDU;
    public javax.swing.JLabel lblIdUser;
    private javax.swing.JLabel lblImagenU;
    public javax.swing.JLabel lblInsertar;
    public javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblNombreU;
    public javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblRangoU;
    public javax.swing.JLabel lblReporteU;
    public javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTItulo;
    private javax.swing.JLabel lblTipoUsuario1;
    private javax.swing.JLabel lblUsuarioU;
    private javax.swing.JPanel pnlDatosU;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlHerramientas;
    private javax.swing.JPanel pnlUsuario;
    public javax.swing.JPasswordField psfContrasena;
    public javax.swing.JTable tblUsuarios;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
