/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Ana
 */
public class FrmJugador extends javax.swing.JFrame {

    /**
     * Creates new form FrmJugador
     */
    public FrmJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondoHerramientas = new javax.swing.JPanel();
        pnlFondoUsuario = new javax.swing.JPanel();
        lblImagenUsuario = new javax.swing.JLabel();
        lblNombreUser = new javax.swing.JLabel();
        lblIdUser = new javax.swing.JLabel();
        lblRangoUauario = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnPrincipiante = new javax.swing.JButton();
        btnIntermedio = new javax.swing.JButton();
        btnAvanzado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MENÚ JUGADOR");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondoHerramientas.setBackground(new java.awt.Color(207, 218, 247));
        pnlFondoHerramientas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondoUsuario.setBackground(new java.awt.Color(10, 17, 68));
        pnlFondoUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenUsuario.setBackground(new java.awt.Color(72, 157, 214));
        lblImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuarioA.png"))); // NOI18N
        pnlFondoUsuario.add(lblImagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 130, 130));

        lblNombreUser.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblNombreUser.setForeground(new java.awt.Color(255, 255, 255));
        pnlFondoUsuario.add(lblNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 170, 180, 30));

        lblIdUser.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblIdUser.setForeground(new java.awt.Color(179, 192, 248));
        pnlFondoUsuario.add(lblIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 50, 20));

        lblRangoUauario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblRangoUauario.setForeground(new java.awt.Color(179, 192, 248));
        pnlFondoUsuario.add(lblRangoUauario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 130, 20));

        pnlFondoHerramientas.add(pnlFondoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 250));

        btnHome.setBackground(new java.awt.Color(102, 105, 126));
        btnHome.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btnHome.setText("  HOME");
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        pnlFondoHerramientas.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 270, 80));

        btnLogout.setBackground(new java.awt.Color(102, 105, 126));
        btnLogout.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        btnLogout.setText("  CERRAR SESIÓN");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlFondoHerramientas.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 270, 80));

        btnPrincipiante.setBackground(new java.awt.Color(102, 105, 126));
        btnPrincipiante.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        btnPrincipiante.setForeground(new java.awt.Color(255, 255, 255));
        btnPrincipiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principiante.png"))); // NOI18N
        btnPrincipiante.setText("  PRINCIPIANTE");
        btnPrincipiante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlFondoHerramientas.add(btnPrincipiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 270, 80));

        btnIntermedio.setBackground(new java.awt.Color(102, 105, 126));
        btnIntermedio.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        btnIntermedio.setForeground(new java.awt.Color(255, 255, 255));
        btnIntermedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/intermedio.png"))); // NOI18N
        btnIntermedio.setText("  INTERMEDIO");
        btnIntermedio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlFondoHerramientas.add(btnIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 270, 80));

        btnAvanzado.setBackground(new java.awt.Color(102, 105, 126));
        btnAvanzado.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        btnAvanzado.setForeground(new java.awt.Color(255, 255, 255));
        btnAvanzado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avanzado.png"))); // NOI18N
        btnAvanzado.setText("  AVANZADO");
        btnAvanzado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlFondoHerramientas.add(btnAvanzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 270, 80));

        getContentPane().add(pnlFondoHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAvanzado;
    public javax.swing.JButton btnHome;
    public javax.swing.JButton btnIntermedio;
    public javax.swing.JButton btnLogout;
    public javax.swing.JButton btnPrincipiante;
    public javax.swing.JLabel lblIdUser;
    private javax.swing.JLabel lblImagenUsuario;
    public javax.swing.JLabel lblNombreUser;
    public javax.swing.JLabel lblRangoUauario;
    private javax.swing.JPanel pnlFondoHerramientas;
    private javax.swing.JPanel pnlFondoUsuario;
    // End of variables declaration//GEN-END:variables
}
