package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    FondoPanel fondo = new FondoPanel();
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDos = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlUno = new FondoPanel();
        btnIngresar = new javax.swing.JButton();
        txtNombreUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        lblImagenUsuario = new javax.swing.JLabel();
        lblContasena = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblAdvertencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDos.setBackground(new java.awt.Color(255, 255, 255));
        pnlDos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/titulo.png"))); // NOI18N
        pnlDos.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        getContentPane().add(pnlDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 450, 630));

        pnlUno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresar.setBackground(new java.awt.Color(255, 97, 126));
        btnIngresar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INGRESAR");
        btnIngresar.setBorder(null);
        pnlUno.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 140, 60));

        txtNombreUsuario.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtNombreUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlUno.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 280, 30));

        txtContrasena.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlUno.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 280, 30));

        lblImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        pnlUno.add(lblImagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        lblContasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/candado.png"))); // NOI18N
        pnlUno.add(lblContasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 40, 50));

        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nombreUsuario.png"))); // NOI18N
        pnlUno.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 40, 50));

        lblAdvertencia.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblAdvertencia.setForeground(new java.awt.Color(255, 255, 255));
        pnlUno.add(lblAdvertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 280, 30));

        getContentPane().add(pnlUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIngresar;
    public javax.swing.JLabel lblAdvertencia;
    private javax.swing.JLabel lblContasena;
    private javax.swing.JLabel lblImagenUsuario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlDos;
    private javax.swing.JPanel pnlUno;
    public javax.swing.JPasswordField txtContrasena;
    public javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables

    //Para poner una imagen de fondo
    class FondoPanel extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/img/fondo1.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            //Es 'false' para que muestre la imagen de fondo
            setOpaque(false);
            //Permite que aparezcan todos los componentes
            super.paint(g);
        }
    }
}